### ISSUE TITLE
Replace CreateEvents data with firebase data

### ISSUE THREAD

**Issue by danielrasmuson** [danielrasmuson/FastEvents#3]
Remove hardcoded user data and instead use firebase wrapper [example](https://github.com/danielrasmuson/FastEvents/blob/master/Server/Scripts/createEvents_TEST.js#L12)

**Comment by jakegarelick** [comment]
![Alt Text](http://i.imgur.com/uxuwK.gif)

**Comment by danielrasmuson** [comment]
@jakegarelick LOL
